name: 'northern_ireland_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  northern_ireland_project:
    transformed:
      crime:
        +materialized: table
        +tags: ["crime_data"]
      dwelling:
        +materialized: table
        +tags: ["dwelling_data"]